services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest

    container_name: biblioteca-sqlserver

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}

    ports:
      - "${MSSQL_PORT}:1433"

    volumes:
      - sqlserver_data:/var/opt/mssql

    restart: unless-stopped

volumes:
  sqlserver_data: