CREATE TABLE Lector (
	numLector INT IDENTITY(1,1) NOT NULL,

	nombre NVARCHAR(100) NOT NULL,
	apellido NVARCHAR(100) NOT NULL,
	cuil NCHAR(11) UNIQUE NOT NULL ,
	telefono VARCHAR(15) NOT NULL,

	CONSTRAINT PK_Lector PRIMARY KEY (numLector)
);